const state={businessType:'',stage:'',customers:'',staff:'',needs:new Set(),name:'',businessName:'',phone:'',email:'',opening:''};
const MODULES={
 foundation:{name:'Digital Business Foundation',setup:55000,monthly:15000,desc:'Professional web presence, lead capture, WhatsApp integration, analytics, hosting and core support'},
 booking:{name:'Booking & Scheduling',setup:30000,monthly:5000,desc:'Online appointment booking, confirmations and schedule workflow'},
 crm:{name:'Customer Records / CRM',setup:25000,monthly:4000,desc:'Customer profiles, interaction history and organised follow-up'},
 orders:{name:'Online Ordering Workflow',setup:35000,monthly:6000,desc:'Digital ordering or menu workflow with order management'},
 inventory:{name:'Inventory & Stock Tracking',setup:40000,monthly:6000,desc:'Stock records, low-stock visibility and inventory workflow'},
 staff:{name:'Staff Operations Dashboard',setup:30000,monthly:5000,desc:'Staff-facing workflow, status updates and operational controls'},
 pos:{name:'POS / Counter Operations',setup:65000,monthly:10000,desc:'Counter sales and operations workflow; hardware not included'},
 ai:{name:'AI Customer Assistant',setup:35000,monthly:6000,desc:'Business-trained 24/7 customer enquiry and lead-assistance layer'},
 automation:{name:'Business Automation',setup:45000,monthly:7000,desc:'Notifications, reminders, quotations or repetitive workflow automation'},
 reporting:{name:'Management Reporting',setup:25000,monthly:4000,desc:'Owner-level operational reporting and performance visibility'}
};
const typeDefaults={
 salon:['foundation','booking','crm'],
 food:['foundation','orders','inventory','reporting'],
 retail:['foundation','inventory','crm','reporting'],
 contractor:['foundation','crm','automation'],
 professional:['foundation','booking','crm'],
 property:['foundation','crm','automation'],
 logistics:['foundation','crm','staff','reporting'],
 other:['foundation']
};
const steps=[
 {key:'businessType',title:'What kind of business are you planning or operating?',sub:'This gives us the starting configuration.',choices:[['salon','Salon / barber / spa'],['food','Restaurant / café / food'],['retail','Retail / shop'],['contractor','Contractor / trades'],['professional','Professional service'],['property','Property / rental'],['logistics','Courier / logistics'],['other','Other']]},
 {key:'stage',title:'Where is the business right now?',sub:'We use this to frame the recommendation and implementation timing.',choices:[['planning','Planning / business plan'],['financing','Preparing financing application'],['approved','Financing approved / ready to launch'],['operating','Already operating']]},
 {key:'customers',title:'How will customers mainly interact with you?',sub:'Choose the closest primary pattern.',choices:[['appointments','Appointments / bookings'],['orders','Orders / purchases'],['quotes','Request quotations'],['walkin','Mostly walk-in / counter'],['mixed','A mix of these']]},
 {key:'staff',title:'How many people will need to use the system?',sub:'An estimate is enough for this budget.',choices:[['1','Owner only'],['2-5','2–5 people'],['6-15','6–15 people'],['16+','16+ people']]},
 {key:'needs',title:'What does the business need to manage?',sub:'Select everything that applies. The quote only adds modules that match your answers.',multi:true,choices:[['booking','Appointments / schedules'],['orders','Online orders'],['inventory','Inventory / stock'],['crm','Customer records'],['staff','Staff workflows'],['pos','POS / counter sales'],['ai','24/7 customer responses'],['automation','Quotations / reminders / automation'],['reporting','Owner reports / analytics']]},
 {key:'contact',title:'Where should we attach this assessment?',sub:'This creates your SnapNest reference so the plan can be retrieved later.',contact:true}
];
let step=0;
function money(n){return 'GYD '+n.toLocaleString('en-US')}
function render(){
 const s=steps[step], box=document.getElementById('qbox'); document.getElementById('bar').style.width=((step+1)/steps.length*100)+'%'; document.getElementById('stepText').textContent=`Step ${step+1} of ${steps.length}`;
 let html=`<h2>${s.title}</h2><p class="muted">${s.sub}</p>`;
 if(s.choices){html+='<div class="choice-grid">'+s.choices.map(([v,l])=>`<button type="button" class="choice ${isSelected(s.key,v)?'selected':''}" onclick="choose('${s.key}','${v}',${s.multi?1:0})">${l}</button>`).join('')+'</div>'}
 if(s.contact){html+=`<div class="field"><label>Your name</label><input id="r_name" value="${state.name}" placeholder="Your full name"></div><div class="field"><label>Business name</label><input id="r_business" value="${state.businessName}" placeholder="Business name or proposed name"></div><div class="field"><label>WhatsApp / phone</label><input id="r_phone" value="${state.phone}" placeholder="+592"></div><div class="field"><label>Email</label><input id="r_email" type="email" value="${state.email}" placeholder="you@example.com"></div><div class="field"><label>Expected opening / implementation timing</label><select id="r_opening"><option value="">Select one</option><option ${state.opening==='0-30'?'selected':''} value="0-30">Within 30 days</option><option ${state.opening==='1-3'?'selected':''} value="1-3">1–3 months</option><option ${state.opening==='3+'?'selected':''} value="3+">More than 3 months</option><option ${state.opening==='unknown'?'selected':''} value="unknown">Not sure yet</option></select></div>`}
 html+=`<div class="tool-actions"><button class="btn" ${step===0?'disabled':''} onclick="prevStep()">Back</button><button class="btn btn-primary" onclick="nextStep()">${step===steps.length-1?'Generate Technology Budget':'Continue'}</button></div>`; box.innerHTML=html;
}
function isSelected(k,v){return k==='needs'?state.needs.has(v):state[k]===v}
function choose(k,v,multi){if(multi){state.needs.has(v)?state.needs.delete(v):state.needs.add(v)}else state[k]=v;render()}
function prevStep(){if(step>0){step--;render()}}
function nextStep(){const s=steps[step]; if(s.contact){state.name=document.getElementById('r_name').value.trim();state.businessName=document.getElementById('r_business').value.trim();state.phone=document.getElementById('r_phone').value.trim();state.email=document.getElementById('r_email').value.trim();state.opening=document.getElementById('r_opening').value;if(!state.name||!state.businessName||!state.phone){alert('Please add your name, business name and WhatsApp / phone number.');return}generate();return}if(s.key==='needs'&&state.needs.size===0){alert('Select at least one requirement.');return}if(!state[s.key]){alert('Choose the option that best fits your business.');return}step++;render()}
function recommendation(){const mods=new Set(typeDefaults[state.businessType]||['foundation']);state.needs.forEach(x=>mods.add(x));if(state.customers==='appointments')mods.add('booking');if(state.customers==='orders')mods.add('orders');if(state.customers==='quotes')mods.add('automation');if(state.customers==='walkin')mods.add('pos');if(state.customers==='mixed'){mods.add('crm');mods.add('reporting')}if(state.staff!=='1')mods.add('staff');return [...mods].filter(x=>MODULES[x])}
function ref(){const d=new Date();const yy=d.getFullYear();const mm=String(d.getMonth()+1).padStart(2,'0');const dd=String(d.getDate()).padStart(2,'0');const rnd=Math.floor(1000+Math.random()*9000);return `SN-BR-${yy}${mm}${dd}-${rnd}`}
async function logAssessment(data){const body=new URLSearchParams({"form-name":"business-readiness",...data});try{await fetch('/',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:body.toString()})}catch(e){console.warn('Assessment logging failed',e)}}
function generate(){const ids=recommendation(), reference=ref();let setup=0,monthly=0;const rows=ids.map(id=>{const m=MODULES[id];setup+=m.setup;monthly+=m.monthly;return `<tr><td><strong>${m.name}</strong><br><span class="muted">${m.desc}</span></td><td>${money(m.setup)}</td><td>${money(m.monthly)}</td></tr>`}).join('');const yearRecurring=monthly*12,total=setup+yearRecurring;const complexity=ids.length;const timeline=complexity<=3?'Approximately 5–10 business days':complexity<=6?'Approximately 10–20 business days':'Phased implementation; initial core approximately 15–25 business days';
 document.getElementById('tool').style.display='none';const r=document.getElementById('result');r.classList.add('show');r.innerHTML=`<div class="quote"><div class="quote-head"><div><span class="badge-green">Budgetary Technology Quotation</span><h2 style="font-family:Fraunces,serif;margin-top:10px">${state.businessName}</h2><p class="muted">Prepared by SnapNest Digital Solutions · Georgetown, Guyana</p></div><div><div class="quote-ref">${reference}</div><div class="muted">${new Date().toLocaleDateString('en-GB')}</div></div></div><p><strong>Assessment summary:</strong> ${labelBusiness(state.businessType)} · ${labelStage(state.stage)} · ${labelStaff(state.staff)} system users.</p><table class="quote-table"><thead><tr><th>Recommended technology</th><th>Implementation</th><th>Monthly</th></tr></thead><tbody>${rows}</tbody></table><div class="totals"><div class="total-line"><span>One-time implementation</span><strong>${money(setup)}</strong></div><div class="total-line"><span>Estimated monthly platform/support</span><strong>${money(monthly)}</strong></div><div class="total-line"><span>12-month recurring budget</span><strong>${money(yearRecurring)}</strong></div><div class="total-line grand"><span>Estimated year-one technology allocation</span><strong>${money(total)}</strong></div></div><div class="note"><strong>Pre-implementation plan:</strong> ${timeline}. SnapNest can prepare the configuration plan before onboarding; client-specific configuration/development begins after the final scope, service agreement and required payment are completed.</div><p class="disclaimer">This document is an automated preliminary budgetary quotation based on the information supplied in the SnapNest Business Technology Readiness assessment. It is intended to assist with business planning and budgeting. It is not a lender approval, guarantee of financing, or final contract. Final scope, integrations, hardware, third-party subscriptions, taxes and exceptional requirements may change the quoted amount. A final SnapNest proposal/service agreement supersedes this assessment.</p><div class="actions no-print"><button class="btn btn-primary" onclick="window.print()">Print / Save as PDF</button><a class="btn" href="https://wa.me/5926704893?text=${encodeURIComponent('Hi SnapNest, my Business Readiness reference is '+reference)}">Discuss This Assessment</a><button class="btn" onclick="location.reload()">Start Another</button></div></div>`;
 logAssessment({reference,name:state.name,business_name:state.businessName,whatsapp:state.phone,email:state.email,business_type:state.businessType,stage:state.stage,customer_flow:state.customers,staff:state.staff,needs:[...state.needs].join(', '),recommended_modules:ids.join(', '),setup_estimate:setup,monthly_estimate:monthly,year_one_estimate:total,opening_timing:state.opening});
}
function labelBusiness(v){return ({salon:'Salon / barber / spa',food:'Restaurant / café / food',retail:'Retail / shop',contractor:'Contractor / trades',professional:'Professional service',property:'Property / rental',logistics:'Courier / logistics',other:'Other business'})[v]||v}
function labelStage(v){return ({planning:'Planning / business plan',financing:'Preparing financing application',approved:'Financing approved / ready to launch',operating:'Already operating'})[v]||v}
function labelStaff(v){return ({'1':'Owner only','2-5':'2–5','6-15':'6–15','16+':'16+'})[v]||v}
render();
